apiVersion: v1
kind: Pod

metadata:
  name: simple-webapp-red
  labels:
    name: simple-webapp

spec:
  containers:
  - name: simple-webapp
    image: mmumshad/simple-webapp-color
    env:
      - name: COLOR
        value: "red"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080